version: '3.8'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend

  apache:
    build: ./apache
    ports:
      - "443:443"
    volumes:
      - apache_certs:/etc/ssl/certs
      - apache_keys:/etc/ssl/private
      - ./web_files:/var/www/html
    depends_on:
      - mysql
      - tomcat
    networks:
      - backend
      - frontend

  tomcat:
    build: ./tomcat
    ports:
      - "8443:8443"
    volumes:
      - tomcat_conf:/opt/tomcat/conf
    networks:
      - backend
      - frontend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - backend
    depends_on:
      - mysql

volumes:
  mysql_data:
  apache_certs:
  apache_keys:
  tomcat_conf:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge