# Tips: When using docker desktop (windows use LF bottom right corner VsCode)
# Linux  uses CRLF
services:
# Use root/example as user/password credentials
  database:
    container_name: l-e-a-p_mysql
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    container_name: l-e-a-p_pma
    image: phpmyadmin
    restart: always
    environment:
      # - PMA_ARBITRARY=1 # Option server connection, enable if you want to connect to other mysql server outside docker network
      - PMA_HOST=database
      - PMA_ABSOLUTE_URI=http://localhost/phpmyadmin
    depends_on:
      - database
    networks:
      - backend

  tomcat:
    container_name: l-e-a-p_tomcat
    build: ./docker-compose/tomcat
    expose:
      - "8443"
    ports:
      - "10.20.0.2:8443:8443" # Port forwarding untuk akses manager tomcat tanpa apache2
      
    volumes:
      - ./app/webapps:/usr/local/tomcat/webapps # Save aplikasi web
      - ./webserver/tomcat-cert:/usr/local/tomcat/conf/ssl/ # Save sertifikat ssl
    networks:
      - backend # backend bertujuan untuk menghubungkan individual container karena network masing2 terisolasi
  apache2:
    build: ./docker-compose/apache2
    container_name: l-e-a-p_apache2
    ports:
      - "443:443"
    volumes:
      - ./webserver/apache2-cert:/usr/local/apache2/ssl # ← PATH CHANGED
    depends_on:
      - tomcat
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge # bridge sebagai jembatan (apache2->tomcat) atau (apache2->pma->mysql)
  backend:
    driver: bridge