version = 5.7.0
archive_dir = /etc/letsencrypt/archive/l-e-a-p.softether.net
cert = /etc/letsencrypt/live/l-e-a-p.softether.net/cert.pem
privkey = /etc/letsencrypt/live/l-e-a-p.softether.net/privkey.pem
chain = /etc/letsencrypt/live/l-e-a-p.softether.net/chain.pem
fullchain = /etc/letsencrypt/live/l-e-a-p.softether.net/fullchain.pem
[renewalparams]
account = 401d6d41243e499ff57b116faf0dbddf
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
l-e-a-p.softether.net = /var/www/certbot
